site_name: fsfs-tong
site_description: Free Software, Free Society 3rd ed, Chinese Translation
site_author: Beijing GNU/Linux User Group

repo_url: https://github.com/tonghuix/fsfs-zh/

pages:
- Foreword to the Third Edition: foreword-v3.md
- Foreword to the First Edition: foreword-v1.md
- Preface: preface-v3.md
- Part One:
  - What Is Free Software?: free-sw.md
  - The GNU Project: thegnuproject.md
  - The Initial Announcement of the GNU Operating System: initial-announcement.md
  - Free Software Is Even More Important Now: free-software-even-more-important.md
  - Why Schools Should Exclusively Use Free Software: edu-schools.md
  - Measures Governments Can Use to Promote Free Software: government-free-software.md
  - Why Free Software Needs Free Documentation: free-doc.md
  - Selling Free Software: selling.md
  - Applying the Free Software Criteria: applying-free-sw-criteria.md
- Part Two:
  - What’s in a Name?: why-gnu-linux.md
  - Linux and the GNU System: linux-and-gnu.md
  - Categories of Free and Nonfree Software: categories.md
  - Why Open Source Misses the Point of Free Software: open-source-misses-the-point.md
  - Did You Say “Intellectual Property”? It’s a Seductive Mirage: not-ipr.md
  - Why Call It the Swindle?: why-call-it-the-swindle.md
  - Words to Avoid  or Use with Care Because They Are Loaded or Confusing: words-to-avoid.md
- Part Three:
  - The Right to Read: right-to-read.md
  - Misinterpreting Copyright—A Series of Errors: misinterpreting-copyright.md
  - Science Must Push Copyright Aside: push-copyright-aside.md
  - Copyright vs. Community in the Age of Computer Networks: copyright-vs-community.md
- Part Four:
  - Software Patents and Literary Patents: software-literary-patents.md
  - The Danger of Software Patents: danger-of-software-patents.md
  - Giving the Software Field Protection from Patents: limit-patent-effect.md
- Part Five:
  - Introduction to the Licenses: licenses-introduction.md
  - How to Choose a License for Your Own Work: license-recommendations.md
  - The X Window System Trap: x.md
  - Programs Must Not Limit the Freedom to Run Them: programs-must-not-limit-freedom-to-run.md
  - What Is Copyleft?: copyleft.md
  - Why Copyleft?: why-copyleft.md
  - Copyleft：Pragmatic Idealism: pragmatic.md
  - The GNU General Public License: gpl.md
  - Why Upgrade to GPLv3: rms-why-gplv3.md
  - The GNU Lesser General Public License: lgpl.md
  - GNU Free Documentation License: fdl.md
  - On Selling Exceptions to the GNU GPL: selling-exceptions.md
- Part Six:
  - Can You Trust Your Computer?: can-you-trust.md
  - The JavaScript Trap: javascript-trap.md
  - Releasing Free Software If You Work at a University: university.md
  - Nonfree DRM’d Games on GNU/Linux：Good or Bad?: nonfree-games.md
  - The Danger of E-Books: the-danger-of-ebooks.md
  - E-books Must Increase Our Freedom, Not Decrease It: ebooks-must-increase-freedom.md
  - Who Does That Server Really Serve?: who-does-that-server-really-serve.md
- Part Seven:
  - Avoiding Ruinous Compromises: compromise.md
  - Overcoming Social Inertia: social-inertia.md
  - Freedom or Power?: freedom-or-power.md
  - Imperfection Is Not the Same as Oppression: imperfection-isnt-oppression.md
  - How Much Surveillance Can Democracy Withstand?: surveillance-vs-democracy.md
- Appendix
  - A Note on Software:appendix-a.md
  - B Translations of “Free Software” and “Gratis Software”:appendix-b.md
  - C The Free Software Song:appendix-c.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition: